import { expect, test } from '@playwright/test'

import { collectConsoleIssues, downloadByButton, login, setNumberInput } from './helpers'

test.describe('考试管理', () => {
  test('题库管理支持搜索、新建和编辑取消', async ({ page }) => {
    const consoleIssues = collectConsoleIssues(page)
    await login(page)

    await page.getByRole('menuitem', { name: '题库管理' }).click()
    await expect(page.getByRole('heading', { name: '题库管理' })).toBeVisible()
    await page.getByPlaceholder('搜索题库或分类').fill('英语')
    await page.getByRole('button', { name: '搜索' }).click()
    await expect(page.getByText('英语基础题库')).toBeVisible()
    await page.getByRole('button', { name: '新建题库' }).click()
    const bankDialog = page.getByRole('dialog', { name: '新建题库' })
    const bankName = `浏览器题库${Date.now()}`
    await bankDialog.getByLabel('名称').fill(bankName)
    await bankDialog.getByLabel('说明').fill('Playwright 创建题库')
    await bankDialog.getByRole('button', { name: '保存' }).click()
    await expect(page.getByText('题库已创建')).toBeVisible()
    await page.getByPlaceholder('搜索题库或分类').fill(bankName)
    await page.getByRole('button', { name: '搜索' }).click()
    const bankRow = page.getByRole('row').filter({ hasText: bankName })
    await expect(bankRow).toBeVisible()
    await bankRow.getByRole('button', { name: '编辑' }).click()
    await expect(page.getByRole('dialog', { name: '编辑题库' })).toBeVisible()
    await page.getByRole('dialog', { name: '编辑题库' }).getByRole('button', { name: '取消' }).click()

    expect(consoleIssues).toEqual([])
  })

  test('试题管理支持模板下载、导入、筛选、搜索、新建、上传和 URL 附件', async ({ page }) => {
    const consoleIssues = collectConsoleIssues(page)
    await login(page)

    await page.getByRole('menuitem', { name: '试题管理' }).click()
    await expect(page.getByRole('heading', { name: '试题管理' })).toBeVisible()
    const questionTemplate = await downloadByButton(page, '下载模板')
    await page.locator('.admin-page header input[type=file]').setInputFiles(questionTemplate)
    await expect(page.getByText('导入完成：成功')).toBeVisible()
    await page.locator('.toolbar__select').click()
    await page.getByRole('option', { name: '英语基础题库' }).click()
    await page.getByPlaceholder('搜索题干或题库').fill('Choose')
    await page.getByRole('button', { name: '搜索' }).click()
    await expect(page.getByText('Choose the correct sentence.').first()).toBeVisible()
    await page.getByRole('button', { name: '新建试题' }).click()
    const questionDialog = page.getByRole('dialog', { name: '新建试题' })
    await questionDialog.getByLabel('题干').fill(`浏览器创建试题 ${Date.now()}`)
    await questionDialog.locator('.option-row').nth(0).getByPlaceholder('选项内容').fill('正确选项')
    await questionDialog.locator('.option-row').nth(1).getByPlaceholder('选项内容').fill('错误选项')
    await questionDialog.getByRole('button', { name: '增加选项' }).click()
    await questionDialog.locator('.option-row').last().getByPlaceholder('选项内容').fill('干扰选项')
    await questionDialog.locator('input[type=file]').setInputFiles('public/local-assets/noun-example.png')
    await expect(page.getByText('附件已上传')).toBeVisible()
    await questionDialog.getByPlaceholder('输入图片、音频、视频或文件 URL').fill('/local-assets/improve-card.jpg')
    await questionDialog.getByRole('button', { name: '添加 URL' }).click()
    await questionDialog.getByLabel('解析').fill('浏览器验收解析')
    await questionDialog.getByRole('button', { name: '保存' }).click()
    await expect(page.getByText('试题已创建')).toBeVisible()

    expect(consoleIssues).toEqual([])
  })

  test('考试管理支持搜索、新建、保存草稿、发布和详情读回', async ({ page }) => {
    const consoleIssues = collectConsoleIssues(page)
    await login(page)

    await page.locator('li.el-menu-item').filter({ hasText: /^考试管理$/ }).click()
    await expect(page.locator('.admin-page__header h1', { hasText: '考试管理' })).toBeVisible()
    await page.getByPlaceholder('搜索考试名称').fill('英语')
    await page.getByRole('button', { name: '搜索' }).click()
    await expect(page.getByText('英语基础模拟考试')).toBeVisible()
    await page.getByRole('button', { name: '新建考试' }).click()
    const examDialog = page.getByRole('dialog', { name: '新建考试' })
    await expect(examDialog.getByText('组卷信息')).toBeVisible()
    await expect(examDialog.getByText('试卷总分')).toBeVisible()
    await examDialog.locator('.rule-item .el-select').first().click()
    await page.getByRole('option', { name: '英语基础题库' }).click()
    const ruleNumbers = examDialog.locator('.rule-fields .el-input-number input')
    await setNumberInput(ruleNumbers.nth(0), '1')
    await setNumberInput(ruleNumbers.nth(1), '5')
    await setNumberInput(ruleNumbers.nth(2), '1')
    await setNumberInput(ruleNumbers.nth(3), '5')
    const examTitle = `浏览器考试 ${Date.now()}`
    await examDialog.getByLabel('考试名称').fill(examTitle)
    await examDialog.getByLabel('考试描述').fill('Playwright 创建考试')
    await examDialog.getByText('限定次数').click()
    await setNumberInput(examDialog.locator('.inline-control .el-input-number input'), '2')
    await examDialog.getByText('整卷一页').click()
    await examDialog.getByText('随机顺序').click()
    await examDialog.getByLabel('开放范围').getByText('公开考试').click()
    await examDialog.getByRole('button', { name: '保存草稿' }).click()
    await expect(page.getByText('草稿已保存')).toBeVisible()
    const savedDialog = page.getByRole('dialog', { name: '编辑考试' })
    await expect(savedDialog.locator('.publish-summary strong').filter({ hasText: /^草稿$/ })).toBeVisible()
    await savedDialog.getByRole('button', { name: '发布考试' }).click()
    await expect(page.getByText('考试已发布')).toBeVisible()
    await expect(savedDialog.locator('.publish-summary strong').filter({ hasText: /^已发布$/ })).toBeVisible()
    await savedDialog.getByRole('button', { name: '取消' }).click()
    await page.getByPlaceholder('搜索考试名称').fill(examTitle)
    await page.getByRole('button', { name: '搜索' }).click()
    await page.getByRole('row').filter({ hasText: examTitle }).getByRole('button', { name: '编辑' }).click()
    const editDialog = page.getByRole('dialog', { name: '编辑考试' })
    await expect(editDialog).toBeVisible()
    await expect(editDialog.locator('.rule-item .el-select')).toContainText('英语基础题库')
    await expect(editDialog.getByText('已发布')).toBeVisible()
    await editDialog.getByRole('button', { name: '取消' }).click()

    expect(consoleIssues).toEqual([])
  })
})
